// Mock data for playlists
export const funnyPlaylists = [
  {
    id: 1,
    title: "SAYA",
    description: "saya saya menba tongtha tong tha menba",
    imageUrl: "",
    songs: 12,
  },
  {
    id: 2,
    title: "WOMEN",
    description: "You're not as good as you think",
    imageUrl: "/placeholder.svg?height=150&width=150",
    songs: 8,
  },
  {
    id: 3,
    title: "BTS",
    description: "Burning dinner never sounded so good",
    imageUrl: "/placeholder.svg?height=150&width=150",
    songs: 15,
  },
  {
    id: 4,
    title: "Elevator Music for Your Home Elevator",
    description: "You don't have a home elevator? Awkward...",
    imageUrl: "/placeholder.svg?height=150&width=150",
    songs: 10,
  },
  {
    id: 5,
    title: "Rick Astley's Greatest Hit",
    description: "Yes, it's just one song repeated",
    imageUrl: "/placeholder.svg?height=150&width=150",
    songs: 1,
  },
  {
    id: 6,
    title: "Songs Your Parents Think Are 'Hip'",
    description: "Warning: Contains the Macarena",
    imageUrl: "/placeholder.svg?height=150&width=150",
    songs: 9,
  },
]

export interface Song {
  id: number
  title: string
  artist: string
  duration: string
  album?: string
  explicit?: boolean
  coverUrl?: string
}

export interface PlaylistDetails {
  id: number
  title: string
  description: string
  imageUrl: string
  songs: Song[]
  totalSongs: number
}

// Mock data for detailed playlists with songs
export const detailedPlaylists: Record<number, PlaylistDetails> = {
  1: {
    id: 1,
    title: "Songs to Pretend You're Working To",
    description: "For when your boss walks by",
    imageUrl: "/placeholder.svg?height=150&width=150",
    totalSongs: 12,
    songs: [
      {
        id: 101,
        title: "Keyboard Typing Sounds (10 Hour Mix)",
        artist: "Productivity Experts",
        duration: "3:45",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Office Ambience Vol. 1",
      },
      {
        id: 102,
        title: "Conference Call Background Noise",
        artist: "Office Ambience",
        duration: "4:20",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Sounds of Meetings",
      },
      {
        id: 103,
        title: "Serious Business Meeting",
        artist: "Corporate Vibes",
        duration: "2:55",
        explicit: true,
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Boardroom Classics",
      },
      {
        id: 104,
        title: "Pretending to Code",
        artist: "Hackerman",
        duration: "3:12",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Keyboard Warriors",
      },
      {
        id: 105,
        title: "Excel Spreadsheet Symphony",
        artist: "Data Analysts",
        duration: "4:01",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Pivot Tables & Chill",
      },
      {
        id: 106,
        title: "Email Notification Beats",
        artist: "Inbox Zero",
        duration: "3:33",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Reply All",
      },
      {
        id: 107,
        title: "Coffee Machine Ambience",
        artist: "Break Room",
        duration: "2:47",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Office Kitchen Sounds",
      },
      {
        id: 108,
        title: "Printer Jam Blues",
        artist: "IT Support",
        duration: "3:22",
        explicit: true,
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Technical Difficulties",
      },
      {
        id: 109,
        title: "Deadline Approaching",
        artist: "Stress & Anxiety",
        duration: "4:15",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Last Minute Panic",
      },
      {
        id: 110,
        title: "Zoom Meeting Etiquette",
        artist: "Remote Workers",
        duration: "3:05",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "You're on Mute",
      },
      {
        id: 111,
        title: "Pretending to Take Notes",
        artist: "Meeting Survivors",
        duration: "2:59",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Nodding Along",
      },
      {
        id: 112,
        title: "5PM Clock Out Countdown",
        artist: "Freedom Fighters",
        duration: "5:00",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Going Home",
      },
    ],
  },
  2: {
    id: 2,
    title: "Shower Hits (That Sound Terrible Outside the Shower)",
    description: "You're not as good as you think",
    imageUrl: "/placeholder.svg?height=150&width=150",
    totalSongs: 8,
    songs: [
      {
        id: 201,
        title: "Bathroom Acoustics",
        artist: "Tile & Porcelain",
        duration: "3:22",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Shower Sessions",
      },
      {
        id: 202,
        title: "Shampoo Bottle Audience",
        artist: "Soap Opera",
        duration: "4:11",
        explicit: true,
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Lather, Rinse, Repeat",
      },
      {
        id: 203,
        title: "High Note Attempt",
        artist: "Vocal Cords",
        duration: "2:55",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Shower Karaoke",
      },
      {
        id: 204,
        title: "Water Resistant Lyrics",
        artist: "Shower Curtain",
        duration: "3:45",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Steamy Hits",
      },
      {
        id: 205,
        title: "Neighbor's Complaint",
        artist: "Thin Walls",
        duration: "3:01",
        explicit: true,
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Keep It Down",
      },
      {
        id: 206,
        title: "Shower Head Microphone",
        artist: "Bathroom Karaoke",
        duration: "4:20",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Wet & Wild Vocals",
      },
      {
        id: 207,
        title: "Hot Water Running Out",
        artist: "Cold Reality",
        duration: "2:33",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Sudden Temperature Change",
      },
      {
        id: 208,
        title: "Slipped on Soap (The Remix)",
        artist: "Bathroom Hazards",
        duration: "3:15",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Dangerous Performances",
      },
    ],
  },
  3: {
    id: 3,
    title: "Songs to Cook Badly To",
    description: "Burning dinner never sounded so good",
    imageUrl: "/placeholder.svg?height=150&width=150",
    totalSongs: 15,
    songs: [
      {
        id: 301,
        title: "Smoke Alarm Symphony",
        artist: "Kitchen Disasters",
        duration: "3:33",
        explicit: true,
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Burning Sensations",
      },
      {
        id: 302,
        title: "Microwave Ding",
        artist: "Lazy Chefs",
        duration: "0:45",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Quick & Easy",
      },
      {
        id: 303,
        title: "Where's the Salt?",
        artist: "Bland Food",
        duration: "2:22",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Seasoning Struggles",
      },
      {
        id: 304,
        title: "Ordering Takeout Again",
        artist: "Delivery Apps",
        duration: "4:15",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Not Cooking Tonight",
      },
      {
        id: 305,
        title: "Recipe Confusion",
        artist: "Cooking Instructions",
        duration: "3:21",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "What Does Simmer Mean?",
      },
      {
        id: 306,
        title: "Knife Skills (I Still Have All My Fingers)",
        artist: "Amateur Hour",
        duration: "2:55",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Careful Chopping",
      },
      {
        id: 307,
        title: "Pasta Water Boil Over",
        artist: "Stovetop Mess",
        duration: "3:45",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Kitchen Cleanup",
      },
      {
        id: 308,
        title: "Expired Ingredients",
        artist: "Food Poisoning",
        duration: "4:01",
        explicit: true,
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Refrigerator Roulette",
      },
      {
        id: 309,
        title: "Dishes in the Sink",
        artist: "I'll Clean Later",
        duration: "3:12",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Procrastination Plates",
      },
      {
        id: 310,
        title: "Instant Pot Pressure Release",
        artist: "Steam & Panic",
        duration: "2:47",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Kitchen Gadgets",
      },
      {
        id: 311,
        title: "Cooking Wine (Mostly Drinking)",
        artist: "Kitchen Buzz",
        duration: "4:20",
        explicit: true,
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "One for the Recipe",
      },
      {
        id: 312,
        title: "Presentation vs Taste",
        artist: "Instagram Food",
        duration: "3:05",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Looks Good, Tastes Bad",
      },
      {
        id: 313,
        title: "Picky Eater Blues",
        artist: "Family Dinner",
        duration: "2:59",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "I Don't Like This",
      },
      {
        id: 314,
        title: "Leftover Surprise",
        artist: "Fridge Archaeology",
        duration: "3:33",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "What's That Smell?",
      },
      {
        id: 315,
        title: "Delivery is Here!",
        artist: "Doorbell Dash",
        duration: "1:45",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Food's Arrived",
      },
    ],
  },
  4: {
    id: 4,
    title: "Elevator Music for Your Home Elevator",
    description: "You don't have a home elevator? Awkward...",
    imageUrl: "/placeholder.svg?height=150&width=150",
    totalSongs: 10,
    songs: [
      {
        id: 401,
        title: "Going Up?",
        artist: "Floor Numbers",
        duration: "3:15",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Vertical Movement",
      },
      {
        id: 402,
        title: "Awkward Silence with Strangers",
        artist: "Personal Space",
        duration: "4:30",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Uncomfortable Moments",
      },
      {
        id: 403,
        title: "Smooth Jazz for Small Spaces",
        artist: "Claustrophobia",
        duration: "2:45",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Tight Quarters",
      },
      {
        id: 404,
        title: "Staring at the Door",
        artist: "Arrival Anxiety",
        duration: "3:22",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Are We There Yet?",
      },
      {
        id: 405,
        title: "Pretending to Check Phone",
        artist: "Social Avoidance",
        duration: "2:55",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Looking Busy",
      },
      {
        id: 406,
        title: "Weight Capacity Exceeded",
        artist: "Too Many People",
        duration: "3:45",
        explicit: true,
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Overloaded",
      },
      {
        id: 407,
        title: "Saxophone Solo No One Asked For",
        artist: "Kenny G Wannabe",
        duration: "5:01",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Smooth Operator",
      },
      {
        id: 408,
        title: "Out of Order",
        artist: "Take the Stairs",
        duration: "2:33",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Technical Difficulties",
      },
      {
        id: 409,
        title: "Holding the Door",
        artist: "Common Courtesy",
        duration: "3:12",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Polite Society",
      },
      {
        id: 410,
        title: "This is My Floor",
        artist: "Awkward Exit",
        duration: "2:47",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Excuse Me",
      },
    ],
  },
  5: {
    id: 5,
    title: "Rick Astley's Greatest Hit",
    description: "Yes, it's just one song repeated",
    imageUrl: "/placeholder.svg?height=150&width=150",
    totalSongs: 1,
    songs: [
      {
        id: 501,
        title: "Never Gonna Give You Up",
        artist: "Rick Astley",
        duration: "3:33",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Whenever You Need Somebody",
      },
    ],
  },
  6: {
    id: 6,
    title: "Songs Your Parents Think Are 'Hip'",
    description: "Warning: Contains the Macarena",
    imageUrl: "/placeholder.svg?height=150&width=150",
    totalSongs: 9,
    songs: [
      {
        id: 601,
        title: "The Macarena",
        artist: "Los Del Rio",
        duration: "3:33",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Dance Crazes",
      },
      {
        id: 602,
        title: "YMCA",
        artist: "Village People",
        duration: "3:45",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Disco Classics",
      },
      {
        id: 603,
        title: "Who Let The Dogs Out",
        artist: "Baha Men",
        duration: "3:15",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "One-Hit Wonders",
      },
      {
        id: 604,
        title: "Ice Ice Baby",
        artist: "Vanilla Ice",
        duration: "4:30",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "90s Rap",
      },
      {
        id: 605,
        title: "Cotton Eye Joe",
        artist: "Rednex",
        duration: "3:12",
        explicit: true,
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Wedding Reception Classics",
      },
      {
        id: 606,
        title: "Achy Breaky Heart",
        artist: "Billy Ray Cyrus",
        duration: "3:22",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Country Hits",
      },
      {
        id: 607,
        title: "Mambo No. 5",
        artist: "Lou Bega",
        duration: "3:40",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Late 90s Pop",
      },
      {
        id: 608,
        title: "Barbie Girl",
        artist: "Aqua",
        duration: "3:15",
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "Europop",
      },
      {
        id: 609,
        title: "Baby Got Back",
        artist: "Sir Mix-a-Lot",
        duration: "4:22",
        explicit: true,
        coverUrl: "/placeholder.svg?height=40&width=40",
        album: "90s Hip Hop",
      },
    ],
  },
}

// Create a flattened array of all songs for search functionality
export const allSongs: Song[] = Object.values(detailedPlaylists).flatMap((playlist) =>
  playlist.songs.map((song) => ({
    ...song,
    coverUrl: song.coverUrl || playlist.imageUrl,
    album: song.album || playlist.title,
  })),
)
